### PR TITLE
New website for 1.90

### PR DESCRIPTION
**Pull request by KonstantinosSykas**
I've managed to replicate the current live oolite.org site (i.e. the one from 1.90 release).

### CODE REVIEW

**Comment by AnotherCommander** [comment]
Looks good to merge as far as I can tell.

**Comment by KonstantinosSykas** [comment]
Done.

**Comment by stimer** [comment]
I tried change email on bb and IMHO lost access to forum :(
bb don't sent verification email to me :(

**Comment by AnotherCommander** [comment]
@stimer Your bb account has been reactivated. If you need to change your email address, please PM Cody.

**Pull request merged**
